#!/usr/bin/env node

/**
 * Script de auto-setup para Upstash Redis
 *
 * Uso:
 *   node scripts/setup-upstash.js
 *
 * Este script:
 * 1. Verifica si hay credenciales Upstash en .env
 * 2. Si no existen, guía al usuario para crear una cuenta
 * 3. Genera automáticamente el .env con credenciales
 * 4. Valida la conexión a Redis
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import https from 'https';
import readline from 'readline';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.join(__dirname, '..');
const ENV_PATH = path.join(ROOT_DIR, '.env');
const ENV_EXAMPLE_PATH = path.join(ROOT_DIR, '.env.example');

// Colores para terminal
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
};

const log = {
  error: (msg) => console.error(`${colors.red}❌ ${msg}${colors.reset}`),
  success: (msg) => console.log(`${colors.green}✅ ${msg}${colors.reset}`),
  info: (msg) => console.log(`${colors.blue}ℹ️  ${msg}${colors.reset}`),
  warn: (msg) => console.log(`${colors.yellow}⚠️  ${msg}${colors.reset}`),
  title: (msg) => console.log(`\n${colors.cyan}${colors.bright}${msg}${colors.reset}\n`),
};

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (q) => new Promise((resolve) => rl.question(q, resolve));

// Verificar si .env ya existe
const checkEnvExists = () => {
  if (fs.existsSync(ENV_PATH)) {
    const content = fs.readFileSync(ENV_PATH, 'utf-8');
    const hasUpstash = content.includes('UPSTASH_REDIS_REST_URL');
    return { exists: true, hasUpstash };
  }
  return { exists: false, hasUpstash: false };
};

// Crear .env.example si no existe
const createEnvExample = () => {
  if (fs.existsSync(ENV_EXAMPLE_PATH)) return;

  const example = `# === SUPABASE ===
SUPABASE_URL=https://xxxxxx.supabase.co
SUPABASE_SERVICE_ROLE_KEY=eyJhbGc...

# === REDIS (Upstash) ===
# https://upstash.com (free tier)
UPSTASH_REDIS_REST_URL=https://xxxxx-xxxxx.upstash.io
UPSTASH_REDIS_REST_TOKEN=xxxxx_xxxxx

# === STRIPE ===
STRIPE_SECRET_KEY=sk_test_...
STRIPE_WEBHOOK_SECRET=whsec_...

# === JWT ===
JWT_SECRET=tu-secreto-jwt-muy-largo-aqui

# === ENVIRONMENT ===
NODE_ENV=development
PORT=3000

# === CORS ===
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
`;

  fs.writeFileSync(ENV_EXAMPLE_PATH, example);
  log.success(`Creado ${ENV_EXAMPLE_PATH}`);
};

// Guía para crear cuenta Upstash
const guideUpstash = async () => {
  log.title('🚀 Setup Upstash Redis');

  console.log(`
${colors.bright}Pasos:${colors.reset}

1. Abre: ${colors.cyan}https://upstash.com${colors.reset}
2. Haz clic en "Start Free" (sin tarjeta de crédito)
3. Crea cuenta con:
   - Email: (tu email)
   - Password: (tu contraseña)
   - Google SSO (opcional)

4. Una vez dentro:
   - Ve a "Redis" en el menú
   - Haz clic en "Create Database"
   - Nombre: "ABZEND" (o similar)
   - Region: "US-EAST-1" (más cercana a ti)
   - Haz clic en "Create"

5. Copia las credenciales:
   - REST API URL: https://xxxxx.upstash.io
   - REST API Token: xxxxx

${colors.yellow}⏱️  Toma ~2 minutos${colors.reset}
`);

  const ready = await question('¿Ya tienes las credenciales? (s/n): ');

  if (ready.toLowerCase() !== 's') {
    log.warn('Abre https://upstash.com y completa el setup');
    process.exit(1);
  }

  return {
    url: await question('REST API URL: '),
    token: await question('REST API Token: ')
  };
};

// Validar credenciales Upstash
const validateUpstashCredentials = async (url, token) => {
  return new Promise((resolve) => {
    const reqUrl = new URL(url + '/ping');

    const options = {
      hostname: reqUrl.hostname,
      path: reqUrl.pathname,
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      }
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        resolve(res.statusCode === 200);
      });
    });

    req.on('error', () => resolve(false));
    req.setTimeout(5000, () => {
      req.destroy();
      resolve(false);
    });

    req.end();
  });
};

// Generar .env
const generateEnv = (credentials) => {
  const envContent = `# Generated by setup-upstash.js
# Timestamp: ${new Date().toISOString()}

# === SUPABASE ===
SUPABASE_URL=https://xxxxxx.supabase.co
SUPABASE_SERVICE_ROLE_KEY=eyJhbGc...

# === REDIS (Upstash) ===
UPSTASH_REDIS_REST_URL=${credentials.url}
UPSTASH_REDIS_REST_TOKEN=${credentials.token}

# === STRIPE ===
STRIPE_SECRET_KEY=sk_test_...
STRIPE_WEBHOOK_SECRET=whsec_...

# === JWT ===
JWT_SECRET=${generateRandomSecret(32)}

# === ENVIRONMENT ===
NODE_ENV=development
PORT=3000

# === CORS ===
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
`;

  fs.writeFileSync(ENV_PATH, envContent);
  log.success(`Creado ${ENV_PATH}`);
};

// Generar secret aleatorio
const generateRandomSecret = (length) => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};

// Main
const main = async () => {
  log.title('🔧 ABZEND Rate Limiting Setup');

  const envCheck = checkEnvExists();

  // Si .env existe y tiene Upstash, salir
  if (envCheck.exists && envCheck.hasUpstash) {
    log.success('✅ .env ya configurado con Upstash');
    rl.close();
    process.exit(0);
  }

  // Crear .env.example
  createEnvExample();

  // Si .env existe pero NO tiene Upstash
  if (envCheck.exists && !envCheck.hasUpstash) {
    log.warn('.env existe pero sin credenciales Upstash');
    const shouldUpdate = await question('¿Actualizar .env con Upstash? (s/n): ');

    if (shouldUpdate.toLowerCase() !== 's') {
      log.info('Configura manualmente en .env:');
      console.log(`
  UPSTASH_REDIS_REST_URL=https://xxxxx.upstash.io
  UPSTASH_REDIS_REST_TOKEN=xxxxx
      `);
      rl.close();
      process.exit(0);
    }
  }

  // Obtener credenciales
  const credentials = await guideUpstash();

  log.info('Validando credenciales...');
  const isValid = await validateUpstashCredentials(credentials.url, credentials.token);

  if (!isValid) {
    log.error('Credenciales inválidas. Verifica URL y token.');
    rl.close();
    process.exit(1);
  }

  log.success('✅ Credenciales válidas');

  // Generar .env
  generateEnv(credentials);

  // Resumen
  log.title('✅ Setup completado');

  console.log(`
${colors.bright}Próximos pasos:${colors.reset}

1. Instala dependencias:
   ${colors.cyan}npm install${colors.reset}

2. Completa variables en .env:
   - SUPABASE_URL
   - SUPABASE_SERVICE_ROLE_KEY
   - JWT_SECRET (ya generado)
   - STRIPE_SECRET_KEY
   - STRIPE_WEBHOOK_SECRET

3. Inicia el servidor:
   ${colors.cyan}npm run dev${colors.reset}

4. Verifica que rate limiting funciona:
   - Intenta login 10 veces rápidamente
   - En la 11ª vez, deberías recibir 429 (Too Many Requests)

${colors.yellow}📚 Documentación:${colors.reset}
   https://upstash.com/docs/redis/overall/getstarted
`);

  rl.close();
};

main().catch((error) => {
  log.error(error.message);
  rl.close();
  process.exit(1);
});
